name: vian_gettds
services:
  gettds:
    cpu_shares: 90
    command: []
    container_name: GetTDS
    deploy:
      resources:
        limits:
          memory: 3916M
    environment:
      - TZ=Asia/Jakarta
    hostname: GetTDS
    image: 192.168.101.244:5000/gettds
    labels:
      icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcMqvD1-DyczHm1VRPJl2jFVxnwUVJnHU2lA&s
    restart: always
    volumes:
      - type: bind
        source: /DATA/tds_logs
        target: /apps/data/logs
    ports: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: GetTDS is a free software tool written in Delphi (pascal), intended to handle the API over the TDS Web. GetTDS supports a wide range of operations on SQL Server.
  tagline:
    en_us: A free software tool written in Delphi (pascal), intended to handle the API over the TDS Web. GetTDS supports a wide range of operations on SQL Server.
  developer: Vian
  author: VianWatulingas
  icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcMqvD1-DyczHm1VRPJl2jFVxnwUVJnHU2lA&s
  title:
    en_us: GetTDS
  category: Vian
  port_map: '80'